title: GRainDB
description: A Relational-Core Graph-Relational DBMS
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

github:
  repository_url: https://github.com/graindb/graindb
  zip_url: https://github.com/graindb/graindb/archive/refs/heads/master.zip
  another_url: https://github.com/graindb/graindb/archive/refs/heads/master.zip